<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachRepository extends EntityRepository
{
    public function findAllCoachesWithDependencies()
    {
        return $this->createQueryBuilder('c')
            ->select('c, t, cntr')
            ->leftJoin('c.team', 't')
            ->leftJoin('t.country', 'cntr')
            ->orderBy('c.team')
            ->getQuery()
            ->getResult();
    }
}
