<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Team;
use AppBundle\Entity\TournamentGroup;
use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findGamesByGroup($name)
    {
        return $this->createQueryBuilder('g')
            ->select('g, ft, st, tg, ftc, stc')
            ->join('g.firstTeam','ft')
            ->join('g.secondTeam', 'st')
            ->join('ft.country', 'ftc')
            ->join('st.country', 'stc')
            ->join('g.tournamentGroup', 'tg')
            ->where('tg.name = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getResult();

    }

    public function findGamesByTeam(Team $team, $numberOfGames = 4)
    {

        return $this->createQueryBuilder('g')
            ->select('g, ft, st, ftc, stc')
            ->join('g.firstTeam', 'ft')
            ->join('g.secondTeam', 'st')
            ->join('ft.country', 'ftc')
            ->join('st.country', 'stc')
            ->where('g.firstTeam = :id')
            ->orWhere('g.secondTeam = :id')
            ->setParameter('id', $team->getId())
            ->orderBy('g.gameDate', 'DESC')
            ->getQuery()
            ->setMaxResults($numberOfGames)
            ->getResult();
    }



    public function findGameWithDependencies($id)
    {
        return $this->createQueryBuilder('g')
            ->select('g , ft, st, ftc, stc')
            ->join('g.firstTeam', 'ft')
            ->join('g.secondTeam', 'st')
            ->join('ft.country', 'ftc')
            ->join('st.country', 'stc')
            ->where('g.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
