<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TournamentGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentGroupRepository extends EntityRepository
{
    public function findGroupWithDependencies($name)
    {
        return $this->createQueryBuilder('gr')
            ->select('gr, games, teams')
            ->join('gr.games', 'games')
            ->join('gr.teams', 'teams')
            ->where('gr.name = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findAllGroupsWithDependencies()
    {
        return $this->createQueryBuilder('g')
            ->select('g, games, teams ')
            ->join('g.games', 'games')
            ->join('g.teams', 'teams')
            ->getQuery()
            ->getResult();
    }
}
